# Generated by Django 4.1.7 on 2023-03-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=None)),
                ('code', models.CharField(max_length=3, null=None)),
            ],
        ),
        migrations.CreateModel(
            name='Passager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=None)),
                ('surname', models.CharField(default=None, max_length=30, null=None)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.IntegerField()),
                ('date', models.DateField(default=None)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_code', to='airline.airport')),
                ('passager', models.ManyToManyField(blank=True, default=None, to='airline.passager')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_code', to='airline.airport')),
            ],
        ),
    ]
