# Generated by Django 4.1.7 on 2023-03-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_alter_flight_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='passager',
        ),
        migrations.AddField(
            model_name='passager',
            name='flight',
            field=models.ManyToManyField(blank=True, to='airline.flight'),
        ),
    ]
