# Generated by Django 4.1.7 on 2023-03-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0003_remove_flight_passager_passager_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passager',
            name='flight',
            field=models.ManyToManyField(blank=True, related_name='passagers', to='airline.flight'),
        ),
    ]
