# Generated by Django 4.1.7 on 2023-03-18 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0005_remove_passager_flight_passager_flight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passager',
            name='flight',
        ),
        migrations.AddField(
            model_name='passager',
            name='flights',
            field=models.ManyToManyField(related_name='passengers', to='airline.flight'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='airline.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='airline.airport'),
        ),
        migrations.AlterField(
            model_name='passager',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='passager',
            name='surname',
            field=models.CharField(max_length=30),
        ),
    ]
