# Generated by Django 4.1.7 on 2023-03-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0009_passager_flights'),
    ]

    operations = [
        migrations.AddField(
            model_name='passager',
            name='flight',
            field=models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='airline.flight'),
        ),
    ]
