# Generated by Django 4.1.7 on 2023-03-18 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0010_passager_flight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passager',
            name='flights',
        ),
        migrations.AlterField(
            model_name='passager',
            name='flight',
            field=models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lol', to='airline.flight'),
        ),
    ]
