# Generated by Django 4.1.7 on 2023-03-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0011_remove_passager_flights_alter_passager_flight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passager',
            name='flight',
        ),
        migrations.AddField(
            model_name='passager',
            name='flights',
            field=models.ManyToManyField(related_name='passengers', to='airline.flight'),
        ),
    ]
